version: '3.8'

services:

  db:

    image: mongo

    restart: always

    environment:

      - MONGO_INITDB_DATABASE=<db-name>

    ports:

      - 27017:27017

    volumes:

      - $PWD/data/db:/data/db

volumes:

  db:

    driver: local